services:
  fams:
    container_name: fams
    depends_on:
      middleware:
        condition: service_started
      models:
        condition: service_started
    environment:
      DELAY_THRESHOLD: 2
      DIGITAL_WORKPLACE_URL: http://models:8080/rest
      INPUT_TOPIC: EU_HUMANMANUFACTURING_STREIN
      MIDDLEWARE_URL: middleware:9092
      MODEL_FILE: /exec/data/STRE_Dummy
      OUTPUT_TOPIC: EU_HUMANMANUFACTURING_STREOUT
      SCHEMA_REGISTRY_PASSWORD: $BF_PASSWORD
      SCHEMA_REGISTRY_URL: http://middleware:8081
      SCHEMA_REGISTRY_USERNAME: $BF_USER
      SCHEMA_TYP: EU_HUMANMANUFACTURING_STREOUT
      SLIDING_DURATION: 60
      WINDOW_DURATION: 60
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/stre:0.4
    restart: on-failure:10
    volumes:
    - fams_data:/exec/data:rw
  im:
    container_name: im
    depends_on:
      middleware:
        condition: service_started
      models:
        condition: service_started
    environment:
      DIGITAL_WORKPLACE_PASSWORD: $BF_PASSWORD
      DIGITAL_WORKPLACE_URL: http://models:8080/rest
      DIGITAL_WORKPLACE_USERNAME: $BF_USER
      INTERVENTION_REPOSITORY_FILE: data/interventions.xml
      KAFKA_URL: middleware:9092
      OUTPUT_PAYLOAD: Intervention
      OUTPUT_TOPIC: EU_HUMANMANUFACTURING_INTERVENTION
      SCHEMA_REGISTRY_URL: http://middleware:8081
      SOURCE: InterventionManager
      TIMEOUT: 10
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/im:0.1
    ports:
    - published: 8666
      target: 8666
    restart: on-failure:10
    volumes:
    - ./volumes/init-data/interventions:/exec/data:rw
  kafka-message-model:
    container_name: kafka-message-model
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/kafka-message-model:0.1
    restart: on-failure
    volumes:
    - message_model:/schemas:rw
  kafka-orion-gateway:
    container_name: kafka-orion-gateway
    depends_on:
      middleware:
        condition: service_started
      orion:
        condition: service_started
    environment:
      ORION_BROKER: http://orion:1026/
      ORION_GATEWAY_ENDPOINT: http://kafka-orion-gateway:8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: middleware:9092
      SPRING_KAFKA_PROPERTIES_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      SPRING_KAFKA_PROPERTIES_BASIC_AUTH_USER_INFO: $BF_USER:$BF_PASSWORD
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://middleware:8081
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/kafka-orion-gateway:0.1.6
  middleware:
    container_name: middleware
    depends_on:
      kafka-message-model:
        condition: service_started
    environment:
      ADV_HOST: middleware
      BROKER_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://middleware:9092
      PASSWORD: $BF_PASSWORD
      REGISTRY_PORT: 8081
      REST_PORT: 8082
      USER: $BF_USER
      WEB_PORT: 3040
      ZK_PORT: 3181
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/middleware:0.1
    ports:
    - published: 3040
      target: 3040
    restart: on-failure
    volumes:
    - message_model:/schemas:rw
  models:
    container_name: models
    depends_on:
      middleware:
        condition: service_started
      models_db:
        condition: service_started
    environment:
      ADMIN_PASSWORD: $BF_PASSWORD
      ADMIN_USERNAME: $BF_USER
      INIT_DATA_DIRECTORY: /var/human/init-data
      KAFKA_REST_PASSWORD: $BF_PASSWORD
      KAFKA_REST_URL: http://middleware:8082
      KAFKA_REST_USER: $BF_USER
      KAFKA_URL: middleware:9092
      KARKA_CLIENT_ID: models
      KARKA_GROUP_ID: models
      MQTT_HOST: sensing-layer_mosquitto
      MQTT_PASSWORD: $BF_PASSWORD
      MQTT_PORT: 1883
      MQTT_USER: $BF_USER
      MYSQL_DB: $MODELS_MYSQL_DATABASE
      MYSQL_HOST: models_db
      MYSQL_PASS: $BF_PASSWORD
      MYSQL_PORT: 3306
      MYSQL_USER: $BF_USER
      SCHEMA_REGISTRY_PASSWORD: $BF_PASSWORD
      SCHEMA_REGISTRY_URL: http://middleware:8081
      SCHEMA_REGISTRY_USER: $BF_USER
      ZOOKEEPER_URL: zookeeper:3181
      spring_profiles_active: kafka
    image: registry.gitlab.com/humanufacturing/integration/data-models:1.3
    restart: on-failure
    volumes:
    - ./volumes/init-data:/var/human/init-data:rw
  models_db:
    container_name: models-db
    environment:
      MYSQL_DATABASE: $MODELS_MYSQL_DATABASE
      MYSQL_PASSWORD: $BF_PASSWORD
      MYSQL_ROOT_PASSWORD: $MODELS_MYSQL_ROOT_PASSWORD
      MYSQL_USER: $BF_USER
    image: mysql:5.7
    restart: on-failure
    volumes:
    - models_db_data:/var/lib/mysql:rw
  mongo:
    command: --nojournal
    container_name: mongo
    image: mongo:4.4
  orion:
    command: -dbhost mongo -corsOrigin __ALL -inReqPayloadMaxSize 2097152
    container_name: orion
    depends_on:
      mongo:
        condition: service_started
    image: fiware/orion:3.1.0
    ports:
    - published: 1026
      target: 1026
  worker_data_importer:
    container_name: worker-data-importer
    depends_on:
      models:
        condition: service_started
    environment:
      CRONTAB_SCHEDULE: '* */4 * * *'
      MODELS_PASSWORD: $BF_PASSWORD
      MODELS_URL: $MODELS_URL
      MODELS_USER: $BF_USER
      SPREADSHEET: $SPREADSHEET
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/consensus:0.1.0
    volumes:
    - ./volumes/fields_map.json:/app/fields_map.json:rw
    - ./volumes/service_account.json:/app/service_account.json:rw
version: '2'
volumes:
  fams_data: {}
  message_model: {}
  models_db_data: {}
